---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'pkgbuild'
          pkgname: 'pkgbuilds/dwarfs'

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'srcinfo'
          pkgname: 'pkgbuilds/dwarfs'